// Generated by CoffeeScript 1.4.0
(function() {
  var app, express, middleware, routing, templating;

  process.on('uncaughtException', function(err) {
    console.error(err.stack);
    return process.exit();
  });

  require('coffee-script');

  express = require('express');

  middleware = require('./config/middleware');

  routing = require('./config/routing');

  templating = require('./config/templating');

  app = express();

  templating.configure(app);

  middleware.configure(app);

  routing.configure(app);

  app.listen(app.get('port'), function() {
    return console.log('Listening on port ' + app.get('port'));
  });

}).call(this);
