// Generated by CoffeeScript 1.4.0
(function() {
  var controllers;

  controllers = require('../controllers');

  exports.configure = function(app) {
    app.get('/', controllers.todo.index);
    app.post('/api/todo', controllers.todo.create);
    app.post('/api/todo/:todoId/items', controllers.todo.items.create);
    app.put('/api/todo/:todoId/items/:itemId', controllers.todo.items.save);
    return app["delete"]('/api/todo/:todoId/items/:itemId', controllers.todo.items["delete"]);
  };

}).call(this);
